schema_version: 1

context:
  name: streamlit-keyup
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 1ebda9aa4c715357b6a7abeb7328bcddde1175b905b88035cc4192df6c9ca535

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build >=0.8.4,<0.9.0
  run:
    - python >=${{ python_min }}
    - streamlit >=1.40

tests:
  - python:
      imports:
        - st_keyup
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Streamlit text input that returns value on keyup
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/blackary/streamlit-keyup

extra:
  recipe-maintainers:
    - thewchan
